# Generated by Django 4.0.2 on 2022-02-22 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
